import os
from pathlib import Path

ROOT_DIRECTORY = Path(__file__).resolve().parent
DOWNLOADS_DIRECTORY = 'downloads'
ABS_DOWNLOADS_PATH = str(ROOT_DIRECTORY / DOWNLOADS_DIRECTORY)

REQUEST_TIMEOUT = 408
UNAUTHORIZED = 401
NOT_FOUND = 404
BAD_REQUEST = 400
INTERNAL_SERVER_ERROR = 500

EXPIRY_TIME_MINUTES = 5
TOKEN_LENGTH = 20
